// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace Schemas {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("Signature", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class SignatureType {
        
        private SignedInfoType signedInfoField;
        
        private SignatureValueType signatureValueField;
        
        private KeyInfoType keyInfoField;
        
        private string idField;
        
        /// <remarks/>
        public SignedInfoType SignedInfo {
            get {
                return this.signedInfoField;
            }
            set {
                this.signedInfoField = value;
            }
        }
        
        /// <remarks/>
        public SignatureValueType SignatureValue {
            get {
                return this.signatureValueField;
            }
            set {
                this.signatureValueField = value;
            }
        }
        
        /// <remarks/>
        public KeyInfoType KeyInfo {
            get {
                return this.keyInfoField;
            }
            set {
                this.keyInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignedInfoType {
        
        private SignedInfoTypeCanonicalizationMethod canonicalizationMethodField;
        
        private SignedInfoTypeSignatureMethod signatureMethodField;
        
        private ReferenceType referenceField;
        
        private string idField;
        
        /// <remarks/>
        public SignedInfoTypeCanonicalizationMethod CanonicalizationMethod {
            get {
                return this.canonicalizationMethodField;
            }
            set {
                this.canonicalizationMethodField = value;
            }
        }
        
        /// <remarks/>
        public SignedInfoTypeSignatureMethod SignatureMethod {
            get {
                return this.signatureMethodField;
            }
            set {
                this.signatureMethodField = value;
            }
        }
        
        /// <remarks/>
        public ReferenceType Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignedInfoTypeCanonicalizationMethod {
        
        private string algorithmField;
        
        public SignedInfoTypeCanonicalizationMethod() {
            this.algorithmField = "http://www.w3.org/TR/2001/REC-xml-c14n-20010315";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtTabRubrica/v02_01_00")]
    public partial class TPeriodoValidade {
        
        private string iniValidField;
        
        private string fimValidField;
        
        /// <remarks/>
        public string iniValid {
            get {
                return this.iniValidField;
            }
            set {
                this.iniValidField = value;
            }
        }
        
        /// <remarks/>
        public string fimValid {
            get {
                return this.fimValidField;
            }
            set {
                this.fimValidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtTabRubrica/v02_01_00")]
    public partial class TDadosRubrica {
        
        private string dscRubrField;
        
        private string natRubrField;
        
        private sbyte tpRubrField;
        
        private string codIncCPField;
        
        private string codIncIRRFField;
        
        private string codIncFGTSField;
        
        private string codIncSINDField;
        
        private TDadosRubricaRepDSR repDSRField;
        
        private TDadosRubricaRep13 rep13Field;
        
        private TDadosRubricaRepFerias repFeriasField;
        
        private TDadosRubricaRepAviso repAvisoField;
        
        private decimal fatorRubrField;
        
        private bool fatorRubrFieldSpecified;
        
        private string observacaoField;
        
        private TDadosRubricaIdeProcessoCP ideProcessoCPField;
        
        private TDadosRubricaIdeProcessoIRRF ideProcessoIRRFField;
        
        private TDadosRubricaIdeProcessoFGTS ideProcessoFGTSField;
        
        private TDadosRubricaIdeProcessoSIND ideProcessoSINDField;
        
        /// <remarks/>
        public string dscRubr {
            get {
                return this.dscRubrField;
            }
            set {
                this.dscRubrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string natRubr {
            get {
                return this.natRubrField;
            }
            set {
                this.natRubrField = value;
            }
        }
        
        /// <remarks/>
        public sbyte tpRubr {
            get {
                return this.tpRubrField;
            }
            set {
                this.tpRubrField = value;
            }
        }
        
        /// <remarks/>
        public string codIncCP {
            get {
                return this.codIncCPField;
            }
            set {
                this.codIncCPField = value;
            }
        }
        
        /// <remarks/>
        public string codIncIRRF {
            get {
                return this.codIncIRRFField;
            }
            set {
                this.codIncIRRFField = value;
            }
        }
        
        /// <remarks/>
        public string codIncFGTS {
            get {
                return this.codIncFGTSField;
            }
            set {
                this.codIncFGTSField = value;
            }
        }
        
        /// <remarks/>
        public string codIncSIND {
            get {
                return this.codIncSINDField;
            }
            set {
                this.codIncSINDField = value;
            }
        }
        
        /// <remarks/>
        public TDadosRubricaRepDSR repDSR {
            get {
                return this.repDSRField;
            }
            set {
                this.repDSRField = value;
            }
        }
        
        /// <remarks/>
        public TDadosRubricaRep13 rep13 {
            get {
                return this.rep13Field;
            }
            set {
                this.rep13Field = value;
            }
        }
        
        /// <remarks/>
        public TDadosRubricaRepFerias repFerias {
            get {
                return this.repFeriasField;
            }
            set {
                this.repFeriasField = value;
            }
        }
        
        /// <remarks/>
        public TDadosRubricaRepAviso repAviso {
            get {
                return this.repAvisoField;
            }
            set {
                this.repAvisoField = value;
            }
        }
        
        /// <remarks/>
        public decimal fatorRubr {
            get {
                return this.fatorRubrField;
            }
            set {
                this.fatorRubrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fatorRubrSpecified {
            get {
                return this.fatorRubrFieldSpecified;
            }
            set {
                this.fatorRubrFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string observacao {
            get {
                return this.observacaoField;
            }
            set {
                this.observacaoField = value;
            }
        }
        
        /// <remarks/>
        public TDadosRubricaIdeProcessoCP ideProcessoCP {
            get {
                return this.ideProcessoCPField;
            }
            set {
                this.ideProcessoCPField = value;
            }
        }
        
        /// <remarks/>
        public TDadosRubricaIdeProcessoIRRF ideProcessoIRRF {
            get {
                return this.ideProcessoIRRFField;
            }
            set {
                this.ideProcessoIRRFField = value;
            }
        }
        
        /// <remarks/>
        public TDadosRubricaIdeProcessoFGTS ideProcessoFGTS {
            get {
                return this.ideProcessoFGTSField;
            }
            set {
                this.ideProcessoFGTSField = value;
            }
        }
        
        /// <remarks/>
        public TDadosRubricaIdeProcessoSIND ideProcessoSIND {
            get {
                return this.ideProcessoSINDField;
            }
            set {
                this.ideProcessoSINDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTabRubrica/v02_01_00")]
    public enum TDadosRubricaRepDSR {
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTabRubrica/v02_01_00")]
    public enum TDadosRubricaRep13 {
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTabRubrica/v02_01_00")]
    public enum TDadosRubricaRepFerias {
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTabRubrica/v02_01_00")]
    public enum TDadosRubricaRepAviso {
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTabRubrica/v02_01_00")]
    public partial class TDadosRubricaIdeProcessoCP {
        
        private sbyte tpProcField;
        
        private string nrProcField;
        
        private sbyte extDecisaoField;
        
        /// <remarks/>
        public sbyte tpProc {
            get {
                return this.tpProcField;
            }
            set {
                this.tpProcField = value;
            }
        }
        
        /// <remarks/>
        public string nrProc {
            get {
                return this.nrProcField;
            }
            set {
                this.nrProcField = value;
            }
        }
        
        /// <remarks/>
        public sbyte extDecisao {
            get {
                return this.extDecisaoField;
            }
            set {
                this.extDecisaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTabRubrica/v02_01_00")]
    public partial class TDadosRubricaIdeProcessoIRRF {
        
        private string nrProcField;
        
        /// <remarks/>
        public string nrProc {
            get {
                return this.nrProcField;
            }
            set {
                this.nrProcField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTabRubrica/v02_01_00")]
    public partial class TDadosRubricaIdeProcessoFGTS {
        
        private string nrProcField;
        
        /// <remarks/>
        public string nrProc {
            get {
                return this.nrProcField;
            }
            set {
                this.nrProcField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTabRubrica/v02_01_00")]
    public partial class TDadosRubricaIdeProcessoSIND {
        
        private string nrProcField;
        
        /// <remarks/>
        public string nrProc {
            get {
                return this.nrProcField;
            }
            set {
                this.nrProcField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtTabRubrica/v02_01_00")]
    public partial class TIdeRubrica {
        
        private string codRubrField;
        
        private string ideTabRubrField;
        
        private string iniValidField;
        
        private string fimValidField;
        
        /// <remarks/>
        public string codRubr {
            get {
                return this.codRubrField;
            }
            set {
                this.codRubrField = value;
            }
        }
        
        /// <remarks/>
        public string ideTabRubr {
            get {
                return this.ideTabRubrField;
            }
            set {
                this.ideTabRubrField = value;
            }
        }
        
        /// <remarks/>
        public string iniValid {
            get {
                return this.iniValidField;
            }
            set {
                this.iniValidField = value;
            }
        }
        
        /// <remarks/>
        public string fimValid {
            get {
                return this.fimValidField;
            }
            set {
                this.fimValidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtTabRubrica/v02_01_00")]
    public partial class TEmpregador {
        
        private sbyte tpInscField;
        
        private string nrInscField;
        
        /// <remarks/>
        public sbyte tpInsc {
            get {
                return this.tpInscField;
            }
            set {
                this.tpInscField = value;
            }
        }
        
        /// <remarks/>
        public string nrInsc {
            get {
                return this.nrInscField;
            }
            set {
                this.nrInscField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtTabRubrica/v02_01_00")]
    public partial class TIdeCadastro {
        
        private sbyte tpAmbField;
        
        private sbyte procEmiField;
        
        private string verProcField;
        
        /// <remarks/>
        public sbyte tpAmb {
            get {
                return this.tpAmbField;
            }
            set {
                this.tpAmbField = value;
            }
        }
        
        /// <remarks/>
        public sbyte procEmi {
            get {
                return this.procEmiField;
            }
            set {
                this.procEmiField = value;
            }
        }
        
        /// <remarks/>
        public string verProc {
            get {
                return this.verProcField;
            }
            set {
                this.verProcField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class X509DataType {
        
        private byte[] x509CertificateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] X509Certificate {
            get {
                return this.x509CertificateField;
            }
            set {
                this.x509CertificateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class KeyInfoType {
        
        private X509DataType x509DataField;
        
        private string idField;
        
        /// <remarks/>
        public X509DataType X509Data {
            get {
                return this.x509DataField;
            }
            set {
                this.x509DataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignatureValueType {
        
        private string idField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class TransformType {
        
        private string[] xPathField;
        
        private TTransformURI algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("XPath")]
        public string[] XPath {
            get {
                return this.xPathField;
            }
            set {
                this.xPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TTransformURI Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public enum TTransformURI {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/2000/09/xmldsig#enveloped-signature")]
        httpwwww3org200009xmldsigenvelopedsignature,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/TR/2001/REC-xml-c14n-20010315")]
        httpwwww3orgTR2001RECxmlc14n20010315,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class ReferenceType {
        
        private TransformType[] transformsField;
        
        private ReferenceTypeDigestMethod digestMethodField;
        
        private byte[] digestValueField;
        
        private string idField;
        
        private string uRIField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable=false)]
        public TransformType[] Transforms {
            get {
                return this.transformsField;
            }
            set {
                this.transformsField = value;
            }
        }
        
        /// <remarks/>
        public ReferenceTypeDigestMethod DigestMethod {
            get {
                return this.digestMethodField;
            }
            set {
                this.digestMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DigestValue {
            get {
                return this.digestValueField;
            }
            set {
                this.digestValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class ReferenceTypeDigestMethod {
        
        private string algorithmField;
        
        public ReferenceTypeDigestMethod() {
            this.algorithmField = "http://www.w3.org/2000/09/xmldsig#sha1";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignedInfoTypeSignatureMethod {
        
        private string algorithmField;
        
        public SignedInfoTypeSignatureMethod() {
            this.algorithmField = "http://www.w3.org/2000/09/xmldsig#rsa-sha1";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTabRubrica/v02_01_00")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtTabRubrica/v02_01_00", IsNullable=false)]
    public partial class eSocial {
        
        private eSocialEvtTabRubrica evtTabRubricaField;
        
        private SignatureType signatureField;
        
        /// <remarks/>
        public eSocialEvtTabRubrica evtTabRubrica {
            get {
                return this.evtTabRubricaField;
            }
            set {
                this.evtTabRubricaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public SignatureType Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTabRubrica/v02_01_00")]
    public partial class eSocialEvtTabRubrica {
        
        private TIdeCadastro ideEventoField;
        
        private TEmpregador ideEmpregadorField;
        
        private eSocialEvtTabRubricaInfoRubrica infoRubricaField;
        
        private string idField;
        
        /// <remarks/>
        public TIdeCadastro ideEvento {
            get {
                return this.ideEventoField;
            }
            set {
                this.ideEventoField = value;
            }
        }
        
        /// <remarks/>
        public TEmpregador ideEmpregador {
            get {
                return this.ideEmpregadorField;
            }
            set {
                this.ideEmpregadorField = value;
            }
        }
        
        /// <remarks/>
        public eSocialEvtTabRubricaInfoRubrica infoRubrica {
            get {
                return this.infoRubricaField;
            }
            set {
                this.infoRubricaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTabRubrica/v02_01_00")]
    public partial class eSocialEvtTabRubricaInfoRubrica {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("alteracao", typeof(eSocialEvtTabRubricaInfoRubricaAlteracao))]
        [System.Xml.Serialization.XmlElementAttribute("exclusao", typeof(eSocialEvtTabRubricaInfoRubricaExclusao))]
        [System.Xml.Serialization.XmlElementAttribute("inclusao", typeof(eSocialEvtTabRubricaInfoRubricaInclusao))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTabRubrica/v02_01_00")]
    public partial class eSocialEvtTabRubricaInfoRubricaAlteracao {
        
        private TIdeRubrica ideRubricaField;
        
        private TDadosRubrica dadosRubricaField;
        
        private TPeriodoValidade novaValidadeField;
        
        /// <remarks/>
        public TIdeRubrica ideRubrica {
            get {
                return this.ideRubricaField;
            }
            set {
                this.ideRubricaField = value;
            }
        }
        
        /// <remarks/>
        public TDadosRubrica dadosRubrica {
            get {
                return this.dadosRubricaField;
            }
            set {
                this.dadosRubricaField = value;
            }
        }
        
        /// <remarks/>
        public TPeriodoValidade novaValidade {
            get {
                return this.novaValidadeField;
            }
            set {
                this.novaValidadeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTabRubrica/v02_01_00")]
    public partial class eSocialEvtTabRubricaInfoRubricaExclusao {
        
        private TIdeRubrica ideRubricaField;
        
        /// <remarks/>
        public TIdeRubrica ideRubrica {
            get {
                return this.ideRubricaField;
            }
            set {
                this.ideRubricaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTabRubrica/v02_01_00")]
    public partial class eSocialEvtTabRubricaInfoRubricaInclusao {
        
        private TIdeRubrica ideRubricaField;
        
        private TDadosRubrica dadosRubricaField;
        
        /// <remarks/>
        public TIdeRubrica ideRubrica {
            get {
                return this.ideRubricaField;
            }
            set {
                this.ideRubricaField = value;
            }
        }
        
        /// <remarks/>
        public TDadosRubrica dadosRubrica {
            get {
                return this.dadosRubricaField;
            }
            set {
                this.dadosRubricaField = value;
            }
        }
    }
}
