// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace Schemas {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("Signature", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class SignatureType {
        
        private SignedInfoType signedInfoField;
        
        private SignatureValueType signatureValueField;
        
        private KeyInfoType keyInfoField;
        
        private string idField;
        
        /// <remarks/>
        public SignedInfoType SignedInfo {
            get {
                return this.signedInfoField;
            }
            set {
                this.signedInfoField = value;
            }
        }
        
        /// <remarks/>
        public SignatureValueType SignatureValue {
            get {
                return this.signatureValueField;
            }
            set {
                this.signatureValueField = value;
            }
        }
        
        /// <remarks/>
        public KeyInfoType KeyInfo {
            get {
                return this.keyInfoField;
            }
            set {
                this.keyInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignedInfoType {
        
        private SignedInfoTypeCanonicalizationMethod canonicalizationMethodField;
        
        private SignedInfoTypeSignatureMethod signatureMethodField;
        
        private ReferenceType referenceField;
        
        private string idField;
        
        /// <remarks/>
        public SignedInfoTypeCanonicalizationMethod CanonicalizationMethod {
            get {
                return this.canonicalizationMethodField;
            }
            set {
                this.canonicalizationMethodField = value;
            }
        }
        
        /// <remarks/>
        public SignedInfoTypeSignatureMethod SignatureMethod {
            get {
                return this.signatureMethodField;
            }
            set {
                this.signatureMethodField = value;
            }
        }
        
        /// <remarks/>
        public ReferenceType Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignedInfoTypeCanonicalizationMethod {
        
        private string algorithmField;
        
        public SignedInfoTypeCanonicalizationMethod() {
            this.algorithmField = "http://www.w3.org/TR/2001/REC-xml-c14n-20010315";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtTSVAltContratual/v02_01_00")]
    public partial class TRemun {
        
        private decimal vrSalFxField;
        
        private sbyte undSalFixoField;
        
        private string dscSalVarField;
        
        /// <remarks/>
        public decimal vrSalFx {
            get {
                return this.vrSalFxField;
            }
            set {
                this.vrSalFxField = value;
            }
        }
        
        /// <remarks/>
        public sbyte undSalFixo {
            get {
                return this.undSalFixoField;
            }
            set {
                this.undSalFixoField = value;
            }
        }
        
        /// <remarks/>
        public string dscSalVar {
            get {
                return this.dscSalVarField;
            }
            set {
                this.dscSalVarField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtTSVAltContratual/v02_01_00")]
    public partial class TEmpregador {
        
        private sbyte tpInscField;
        
        private string nrInscField;
        
        /// <remarks/>
        public sbyte tpInsc {
            get {
                return this.tpInscField;
            }
            set {
                this.tpInscField = value;
            }
        }
        
        /// <remarks/>
        public string nrInsc {
            get {
                return this.nrInscField;
            }
            set {
                this.nrInscField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtTSVAltContratual/v02_01_00")]
    public partial class TIdeEveTrab {
        
        private sbyte indRetifField;
        
        private string nrReciboField;
        
        private sbyte tpAmbField;
        
        private sbyte procEmiField;
        
        private string verProcField;
        
        /// <remarks/>
        public sbyte indRetif {
            get {
                return this.indRetifField;
            }
            set {
                this.indRetifField = value;
            }
        }
        
        /// <remarks/>
        public string nrRecibo {
            get {
                return this.nrReciboField;
            }
            set {
                this.nrReciboField = value;
            }
        }
        
        /// <remarks/>
        public sbyte tpAmb {
            get {
                return this.tpAmbField;
            }
            set {
                this.tpAmbField = value;
            }
        }
        
        /// <remarks/>
        public sbyte procEmi {
            get {
                return this.procEmiField;
            }
            set {
                this.procEmiField = value;
            }
        }
        
        /// <remarks/>
        public string verProc {
            get {
                return this.verProcField;
            }
            set {
                this.verProcField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class X509DataType {
        
        private byte[] x509CertificateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] X509Certificate {
            get {
                return this.x509CertificateField;
            }
            set {
                this.x509CertificateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class KeyInfoType {
        
        private X509DataType x509DataField;
        
        private string idField;
        
        /// <remarks/>
        public X509DataType X509Data {
            get {
                return this.x509DataField;
            }
            set {
                this.x509DataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignatureValueType {
        
        private string idField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class TransformType {
        
        private string[] xPathField;
        
        private TTransformURI algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("XPath")]
        public string[] XPath {
            get {
                return this.xPathField;
            }
            set {
                this.xPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TTransformURI Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public enum TTransformURI {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/2000/09/xmldsig#enveloped-signature")]
        httpwwww3org200009xmldsigenvelopedsignature,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/TR/2001/REC-xml-c14n-20010315")]
        httpwwww3orgTR2001RECxmlc14n20010315,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class ReferenceType {
        
        private TransformType[] transformsField;
        
        private ReferenceTypeDigestMethod digestMethodField;
        
        private byte[] digestValueField;
        
        private string idField;
        
        private string uRIField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable=false)]
        public TransformType[] Transforms {
            get {
                return this.transformsField;
            }
            set {
                this.transformsField = value;
            }
        }
        
        /// <remarks/>
        public ReferenceTypeDigestMethod DigestMethod {
            get {
                return this.digestMethodField;
            }
            set {
                this.digestMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DigestValue {
            get {
                return this.digestValueField;
            }
            set {
                this.digestValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class ReferenceTypeDigestMethod {
        
        private string algorithmField;
        
        public ReferenceTypeDigestMethod() {
            this.algorithmField = "http://www.w3.org/2000/09/xmldsig#sha1";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignedInfoTypeSignatureMethod {
        
        private string algorithmField;
        
        public SignedInfoTypeSignatureMethod() {
            this.algorithmField = "http://www.w3.org/2000/09/xmldsig#rsa-sha1";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVAltContratual/v02_01_00")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtTSVAltContratual/v02_01_00", IsNullable=false)]
    public partial class eSocial {
        
        private eSocialEvtTSVAltContr evtTSVAltContrField;
        
        private SignatureType signatureField;
        
        /// <remarks/>
        public eSocialEvtTSVAltContr evtTSVAltContr {
            get {
                return this.evtTSVAltContrField;
            }
            set {
                this.evtTSVAltContrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public SignatureType Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVAltContratual/v02_01_00")]
    public partial class eSocialEvtTSVAltContr {
        
        private TIdeEveTrab ideEventoField;
        
        private TEmpregador ideEmpregadorField;
        
        private eSocialEvtTSVAltContrIdeTrabSemVinculo ideTrabSemVinculoField;
        
        private eSocialEvtTSVAltContrInfoTSVAlteracao infoTSVAlteracaoField;
        
        private string idField;
        
        /// <remarks/>
        public TIdeEveTrab ideEvento {
            get {
                return this.ideEventoField;
            }
            set {
                this.ideEventoField = value;
            }
        }
        
        /// <remarks/>
        public TEmpregador ideEmpregador {
            get {
                return this.ideEmpregadorField;
            }
            set {
                this.ideEmpregadorField = value;
            }
        }
        
        /// <remarks/>
        public eSocialEvtTSVAltContrIdeTrabSemVinculo ideTrabSemVinculo {
            get {
                return this.ideTrabSemVinculoField;
            }
            set {
                this.ideTrabSemVinculoField = value;
            }
        }
        
        /// <remarks/>
        public eSocialEvtTSVAltContrInfoTSVAlteracao infoTSVAlteracao {
            get {
                return this.infoTSVAlteracaoField;
            }
            set {
                this.infoTSVAlteracaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVAltContratual/v02_01_00")]
    public partial class eSocialEvtTSVAltContrIdeTrabSemVinculo {
        
        private string cpfTrabField;
        
        private string nisTrabField;
        
        private string codCategField;
        
        /// <remarks/>
        public string cpfTrab {
            get {
                return this.cpfTrabField;
            }
            set {
                this.cpfTrabField = value;
            }
        }
        
        /// <remarks/>
        public string nisTrab {
            get {
                return this.nisTrabField;
            }
            set {
                this.nisTrabField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string codCateg {
            get {
                return this.codCategField;
            }
            set {
                this.codCategField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVAltContratual/v02_01_00")]
    public partial class eSocialEvtTSVAltContrInfoTSVAlteracao {
        
        private System.DateTime dtAlteracaoField;
        
        private sbyte natAtividadeField;
        
        private bool natAtividadeFieldSpecified;
        
        private eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementares infoComplementaresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dtAlteracao {
            get {
                return this.dtAlteracaoField;
            }
            set {
                this.dtAlteracaoField = value;
            }
        }
        
        /// <remarks/>
        public sbyte natAtividade {
            get {
                return this.natAtividadeField;
            }
            set {
                this.natAtividadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool natAtividadeSpecified {
            get {
                return this.natAtividadeFieldSpecified;
            }
            set {
                this.natAtividadeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementares infoComplementares {
            get {
                return this.infoComplementaresField;
            }
            set {
                this.infoComplementaresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVAltContratual/v02_01_00")]
    public partial class eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementares {
        
        private eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementaresCargoFuncao cargoFuncaoField;
        
        private TRemun remuneracaoField;
        
        private eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementaresInfoEstagiario infoEstagiarioField;
        
        /// <remarks/>
        public eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementaresCargoFuncao cargoFuncao {
            get {
                return this.cargoFuncaoField;
            }
            set {
                this.cargoFuncaoField = value;
            }
        }
        
        /// <remarks/>
        public TRemun remuneracao {
            get {
                return this.remuneracaoField;
            }
            set {
                this.remuneracaoField = value;
            }
        }
        
        /// <remarks/>
        public eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementaresInfoEstagiario infoEstagiario {
            get {
                return this.infoEstagiarioField;
            }
            set {
                this.infoEstagiarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVAltContratual/v02_01_00")]
    public partial class eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementaresCargoFuncao {
        
        private string codCargoField;
        
        private string codFuncaoField;
        
        /// <remarks/>
        public string codCargo {
            get {
                return this.codCargoField;
            }
            set {
                this.codCargoField = value;
            }
        }
        
        /// <remarks/>
        public string codFuncao {
            get {
                return this.codFuncaoField;
            }
            set {
                this.codFuncaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVAltContratual/v02_01_00")]
    public partial class eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementaresInfoEstagiario {
        
        private string natEstagioField;
        
        private sbyte nivEstagioField;
        
        private string areaAtuacaoField;
        
        private string nrApolField;
        
        private decimal vlrBolsaField;
        
        private bool vlrBolsaFieldSpecified;
        
        private System.DateTime dtPrevTermField;
        
        private eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementaresInfoEstagiarioInstEnsino instEnsinoField;
        
        private eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementaresInfoEstagiarioAgeIntegracao ageIntegracaoField;
        
        private eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementaresInfoEstagiarioSupervisorEstagio supervisorEstagioField;
        
        /// <remarks/>
        public string natEstagio {
            get {
                return this.natEstagioField;
            }
            set {
                this.natEstagioField = value;
            }
        }
        
        /// <remarks/>
        public sbyte nivEstagio {
            get {
                return this.nivEstagioField;
            }
            set {
                this.nivEstagioField = value;
            }
        }
        
        /// <remarks/>
        public string areaAtuacao {
            get {
                return this.areaAtuacaoField;
            }
            set {
                this.areaAtuacaoField = value;
            }
        }
        
        /// <remarks/>
        public string nrApol {
            get {
                return this.nrApolField;
            }
            set {
                this.nrApolField = value;
            }
        }
        
        /// <remarks/>
        public decimal vlrBolsa {
            get {
                return this.vlrBolsaField;
            }
            set {
                this.vlrBolsaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vlrBolsaSpecified {
            get {
                return this.vlrBolsaFieldSpecified;
            }
            set {
                this.vlrBolsaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dtPrevTerm {
            get {
                return this.dtPrevTermField;
            }
            set {
                this.dtPrevTermField = value;
            }
        }
        
        /// <remarks/>
        public eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementaresInfoEstagiarioInstEnsino instEnsino {
            get {
                return this.instEnsinoField;
            }
            set {
                this.instEnsinoField = value;
            }
        }
        
        /// <remarks/>
        public eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementaresInfoEstagiarioAgeIntegracao ageIntegracao {
            get {
                return this.ageIntegracaoField;
            }
            set {
                this.ageIntegracaoField = value;
            }
        }
        
        /// <remarks/>
        public eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementaresInfoEstagiarioSupervisorEstagio supervisorEstagio {
            get {
                return this.supervisorEstagioField;
            }
            set {
                this.supervisorEstagioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVAltContratual/v02_01_00")]
    public partial class eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementaresInfoEstagiarioInstEnsino {
        
        private string cnpjInstEnsinoField;
        
        private string nmRazaoField;
        
        private string dscLogradField;
        
        private string nrLogradField;
        
        private string bairroField;
        
        private string cepField;
        
        private string codMunicField;
        
        private string ufField;
        
        /// <remarks/>
        public string cnpjInstEnsino {
            get {
                return this.cnpjInstEnsinoField;
            }
            set {
                this.cnpjInstEnsinoField = value;
            }
        }
        
        /// <remarks/>
        public string nmRazao {
            get {
                return this.nmRazaoField;
            }
            set {
                this.nmRazaoField = value;
            }
        }
        
        /// <remarks/>
        public string dscLograd {
            get {
                return this.dscLogradField;
            }
            set {
                this.dscLogradField = value;
            }
        }
        
        /// <remarks/>
        public string nrLograd {
            get {
                return this.nrLogradField;
            }
            set {
                this.nrLogradField = value;
            }
        }
        
        /// <remarks/>
        public string bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string codMunic {
            get {
                return this.codMunicField;
            }
            set {
                this.codMunicField = value;
            }
        }
        
        /// <remarks/>
        public string uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVAltContratual/v02_01_00")]
    public partial class eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementaresInfoEstagiarioAgeIntegracao {
        
        private string cnpjAgntIntegField;
        
        private string nmRazaoField;
        
        private string dscLogradField;
        
        private string nrLogradField;
        
        private string bairroField;
        
        private string cepField;
        
        private string codMunicField;
        
        private string ufField;
        
        /// <remarks/>
        public string cnpjAgntInteg {
            get {
                return this.cnpjAgntIntegField;
            }
            set {
                this.cnpjAgntIntegField = value;
            }
        }
        
        /// <remarks/>
        public string nmRazao {
            get {
                return this.nmRazaoField;
            }
            set {
                this.nmRazaoField = value;
            }
        }
        
        /// <remarks/>
        public string dscLograd {
            get {
                return this.dscLogradField;
            }
            set {
                this.dscLogradField = value;
            }
        }
        
        /// <remarks/>
        public string nrLograd {
            get {
                return this.nrLogradField;
            }
            set {
                this.nrLogradField = value;
            }
        }
        
        /// <remarks/>
        public string bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string codMunic {
            get {
                return this.codMunicField;
            }
            set {
                this.codMunicField = value;
            }
        }
        
        /// <remarks/>
        public string uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVAltContratual/v02_01_00")]
    public partial class eSocialEvtTSVAltContrInfoTSVAlteracaoInfoComplementaresInfoEstagiarioSupervisorEstagio {
        
        private string cpfSupervisorField;
        
        private string nmSupervField;
        
        /// <remarks/>
        public string cpfSupervisor {
            get {
                return this.cpfSupervisorField;
            }
            set {
                this.cpfSupervisorField = value;
            }
        }
        
        /// <remarks/>
        public string nmSuperv {
            get {
                return this.nmSupervField;
            }
            set {
                this.nmSupervField = value;
            }
        }
    }
}
