// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

// 
//This source code was auto-generated by MonoXSD
//
namespace Schemas {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    [System.Xml.Serialization.XmlRootAttribute("Signature", Namespace="http://www.w3.org/2000/09/xmldsig#", IsNullable=false)]
    public partial class SignatureType {
        
        private SignedInfoType signedInfoField;
        
        private SignatureValueType signatureValueField;
        
        private KeyInfoType keyInfoField;
        
        private string idField;
        
        /// <remarks/>
        public SignedInfoType SignedInfo {
            get {
                return this.signedInfoField;
            }
            set {
                this.signedInfoField = value;
            }
        }
        
        /// <remarks/>
        public SignatureValueType SignatureValue {
            get {
                return this.signatureValueField;
            }
            set {
                this.signatureValueField = value;
            }
        }
        
        /// <remarks/>
        public KeyInfoType KeyInfo {
            get {
                return this.keyInfoField;
            }
            set {
                this.keyInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignedInfoType {
        
        private SignedInfoTypeCanonicalizationMethod canonicalizationMethodField;
        
        private SignedInfoTypeSignatureMethod signatureMethodField;
        
        private ReferenceType referenceField;
        
        private string idField;
        
        /// <remarks/>
        public SignedInfoTypeCanonicalizationMethod CanonicalizationMethod {
            get {
                return this.canonicalizationMethodField;
            }
            set {
                this.canonicalizationMethodField = value;
            }
        }
        
        /// <remarks/>
        public SignedInfoTypeSignatureMethod SignatureMethod {
            get {
                return this.signatureMethodField;
            }
            set {
                this.signatureMethodField = value;
            }
        }
        
        /// <remarks/>
        public ReferenceType Reference {
            get {
                return this.referenceField;
            }
            set {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignedInfoTypeCanonicalizationMethod {
        
        private string algorithmField;
        
        public SignedInfoTypeCanonicalizationMethod() {
            this.algorithmField = "http://www.w3.org/TR/2001/REC-xml-c14n-20010315";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public partial class TCessaoTrab {
        
        private string categOrigField;
        
        private string cnpjCedntField;
        
        private string matricCedField;
        
        private System.DateTime dtAdmCedField;
        
        private sbyte infOnusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string categOrig {
            get {
                return this.categOrigField;
            }
            set {
                this.categOrigField = value;
            }
        }
        
        /// <remarks/>
        public string cnpjCednt {
            get {
                return this.cnpjCedntField;
            }
            set {
                this.cnpjCedntField = value;
            }
        }
        
        /// <remarks/>
        public string matricCed {
            get {
                return this.matricCedField;
            }
            set {
                this.matricCedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dtAdmCed {
            get {
                return this.dtAdmCedField;
            }
            set {
                this.dtAdmCedField = value;
            }
        }
        
        /// <remarks/>
        public sbyte infOnus {
            get {
                return this.infOnusField;
            }
            set {
                this.infOnusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public partial class TFgts {
        
        private string opcFGTSField;
        
        private System.DateTime dtOpcFGTSField;
        
        private bool dtOpcFGTSFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string opcFGTS {
            get {
                return this.opcFGTSField;
            }
            set {
                this.opcFGTSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dtOpcFGTS {
            get {
                return this.dtOpcFGTSField;
            }
            set {
                this.dtOpcFGTSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dtOpcFGTSSpecified {
            get {
                return this.dtOpcFGTSFieldSpecified;
            }
            set {
                this.dtOpcFGTSFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public partial class TRemun {
        
        private decimal vrSalFxField;
        
        private sbyte undSalFixoField;
        
        private string dscSalVarField;
        
        /// <remarks/>
        public decimal vrSalFx {
            get {
                return this.vrSalFxField;
            }
            set {
                this.vrSalFxField = value;
            }
        }
        
        /// <remarks/>
        public sbyte undSalFixo {
            get {
                return this.undSalFixoField;
            }
            set {
                this.undSalFixoField = value;
            }
        }
        
        /// <remarks/>
        public string dscSalVar {
            get {
                return this.dscSalVarField;
            }
            set {
                this.dscSalVarField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public partial class TContato {
        
        private string fonePrincField;
        
        private string foneAlternatField;
        
        private string emailPrincField;
        
        private string emailAlternatField;
        
        /// <remarks/>
        public string fonePrinc {
            get {
                return this.fonePrincField;
            }
            set {
                this.fonePrincField = value;
            }
        }
        
        /// <remarks/>
        public string foneAlternat {
            get {
                return this.foneAlternatField;
            }
            set {
                this.foneAlternatField = value;
            }
        }
        
        /// <remarks/>
        public string emailPrinc {
            get {
                return this.emailPrincField;
            }
            set {
                this.emailPrincField = value;
            }
        }
        
        /// <remarks/>
        public string emailAlternat {
            get {
                return this.emailAlternatField;
            }
            set {
                this.emailAlternatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public partial class TTrabEstrang {
        
        private System.DateTime dtChegadaField;
        
        private sbyte classTrabEstrangField;
        
        private TTrabEstrangCasadoBr casadoBrField;
        
        private TTrabEstrangFilhosBr filhosBrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dtChegada {
            get {
                return this.dtChegadaField;
            }
            set {
                this.dtChegadaField = value;
            }
        }
        
        /// <remarks/>
        public sbyte classTrabEstrang {
            get {
                return this.classTrabEstrangField;
            }
            set {
                this.classTrabEstrangField = value;
            }
        }
        
        /// <remarks/>
        public TTrabEstrangCasadoBr casadoBr {
            get {
                return this.casadoBrField;
            }
            set {
                this.casadoBrField = value;
            }
        }
        
        /// <remarks/>
        public TTrabEstrangFilhosBr filhosBr {
            get {
                return this.filhosBrField;
            }
            set {
                this.filhosBrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public enum TTrabEstrangCasadoBr {
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public enum TTrabEstrangFilhosBr {
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public partial class TEnderecoExterior {
        
        private string paisResidField;
        
        private string dscLogradField;
        
        private string nrLogradField;
        
        private string complementoField;
        
        private string bairroField;
        
        private string nmCidField;
        
        private string codPostalField;
        
        /// <remarks/>
        public string paisResid {
            get {
                return this.paisResidField;
            }
            set {
                this.paisResidField = value;
            }
        }
        
        /// <remarks/>
        public string dscLograd {
            get {
                return this.dscLogradField;
            }
            set {
                this.dscLogradField = value;
            }
        }
        
        /// <remarks/>
        public string nrLograd {
            get {
                return this.nrLogradField;
            }
            set {
                this.nrLogradField = value;
            }
        }
        
        /// <remarks/>
        public string complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
            }
        }
        
        /// <remarks/>
        public string bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        public string nmCid {
            get {
                return this.nmCidField;
            }
            set {
                this.nmCidField = value;
            }
        }
        
        /// <remarks/>
        public string codPostal {
            get {
                return this.codPostalField;
            }
            set {
                this.codPostalField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public partial class TEnderecoBrasil {
        
        private string tpLogradField;
        
        private string dscLogradField;
        
        private string nrLogradField;
        
        private string complementoField;
        
        private string bairroField;
        
        private string cepField;
        
        private string codMunicField;
        
        private string ufField;
        
        /// <remarks/>
        public string tpLograd {
            get {
                return this.tpLogradField;
            }
            set {
                this.tpLogradField = value;
            }
        }
        
        /// <remarks/>
        public string dscLograd {
            get {
                return this.dscLogradField;
            }
            set {
                this.dscLogradField = value;
            }
        }
        
        /// <remarks/>
        public string nrLograd {
            get {
                return this.nrLogradField;
            }
            set {
                this.nrLogradField = value;
            }
        }
        
        /// <remarks/>
        public string complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
            }
        }
        
        /// <remarks/>
        public string bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string codMunic {
            get {
                return this.codMunicField;
            }
            set {
                this.codMunicField = value;
            }
        }
        
        /// <remarks/>
        public string uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public partial class TCnh {
        
        private string nrRegCnhField;
        
        private System.DateTime dtExpedField;
        
        private bool dtExpedFieldSpecified;
        
        private string ufCnhField;
        
        private System.DateTime dtValidField;
        
        private System.DateTime dtPriHabField;
        
        private bool dtPriHabFieldSpecified;
        
        private string categoriaCnhField;
        
        /// <remarks/>
        public string nrRegCnh {
            get {
                return this.nrRegCnhField;
            }
            set {
                this.nrRegCnhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dtExped {
            get {
                return this.dtExpedField;
            }
            set {
                this.dtExpedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dtExpedSpecified {
            get {
                return this.dtExpedFieldSpecified;
            }
            set {
                this.dtExpedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string ufCnh {
            get {
                return this.ufCnhField;
            }
            set {
                this.ufCnhField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dtValid {
            get {
                return this.dtValidField;
            }
            set {
                this.dtValidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dtPriHab {
            get {
                return this.dtPriHabField;
            }
            set {
                this.dtPriHabField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dtPriHabSpecified {
            get {
                return this.dtPriHabFieldSpecified;
            }
            set {
                this.dtPriHabFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string categoriaCnh {
            get {
                return this.categoriaCnhField;
            }
            set {
                this.categoriaCnhField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public partial class TOc {
        
        private string nrOcField;
        
        private string orgaoEmissorField;
        
        private System.DateTime dtExpedField;
        
        private bool dtExpedFieldSpecified;
        
        private System.DateTime dtValidField;
        
        private bool dtValidFieldSpecified;
        
        /// <remarks/>
        public string nrOc {
            get {
                return this.nrOcField;
            }
            set {
                this.nrOcField = value;
            }
        }
        
        /// <remarks/>
        public string orgaoEmissor {
            get {
                return this.orgaoEmissorField;
            }
            set {
                this.orgaoEmissorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dtExped {
            get {
                return this.dtExpedField;
            }
            set {
                this.dtExpedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dtExpedSpecified {
            get {
                return this.dtExpedFieldSpecified;
            }
            set {
                this.dtExpedFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dtValid {
            get {
                return this.dtValidField;
            }
            set {
                this.dtValidField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dtValidSpecified {
            get {
                return this.dtValidFieldSpecified;
            }
            set {
                this.dtValidFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public partial class TRne {
        
        private string nrRneField;
        
        private string orgaoEmissorField;
        
        private System.DateTime dtExpedField;
        
        private bool dtExpedFieldSpecified;
        
        /// <remarks/>
        public string nrRne {
            get {
                return this.nrRneField;
            }
            set {
                this.nrRneField = value;
            }
        }
        
        /// <remarks/>
        public string orgaoEmissor {
            get {
                return this.orgaoEmissorField;
            }
            set {
                this.orgaoEmissorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dtExped {
            get {
                return this.dtExpedField;
            }
            set {
                this.dtExpedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dtExpedSpecified {
            get {
                return this.dtExpedFieldSpecified;
            }
            set {
                this.dtExpedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public partial class TRg {
        
        private string nrRgField;
        
        private string orgaoEmissorField;
        
        private System.DateTime dtExpedField;
        
        private bool dtExpedFieldSpecified;
        
        /// <remarks/>
        public string nrRg {
            get {
                return this.nrRgField;
            }
            set {
                this.nrRgField = value;
            }
        }
        
        /// <remarks/>
        public string orgaoEmissor {
            get {
                return this.orgaoEmissorField;
            }
            set {
                this.orgaoEmissorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dtExped {
            get {
                return this.dtExpedField;
            }
            set {
                this.dtExpedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dtExpedSpecified {
            get {
                return this.dtExpedFieldSpecified;
            }
            set {
                this.dtExpedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public partial class TRic {
        
        private string nrRicField;
        
        private string orgaoEmissorField;
        
        private System.DateTime dtExpedField;
        
        private bool dtExpedFieldSpecified;
        
        /// <remarks/>
        public string nrRic {
            get {
                return this.nrRicField;
            }
            set {
                this.nrRicField = value;
            }
        }
        
        /// <remarks/>
        public string orgaoEmissor {
            get {
                return this.orgaoEmissorField;
            }
            set {
                this.orgaoEmissorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dtExped {
            get {
                return this.dtExpedField;
            }
            set {
                this.dtExpedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dtExpedSpecified {
            get {
                return this.dtExpedFieldSpecified;
            }
            set {
                this.dtExpedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public partial class TCtps {
        
        private string nrCtpsField;
        
        private string serieCtpsField;
        
        private string ufCtpsField;
        
        /// <remarks/>
        public string nrCtps {
            get {
                return this.nrCtpsField;
            }
            set {
                this.nrCtpsField = value;
            }
        }
        
        /// <remarks/>
        public string serieCtps {
            get {
                return this.serieCtpsField;
            }
            set {
                this.serieCtpsField = value;
            }
        }
        
        /// <remarks/>
        public string ufCtps {
            get {
                return this.ufCtpsField;
            }
            set {
                this.ufCtpsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public partial class TEmpregador {
        
        private sbyte tpInscField;
        
        private string nrInscField;
        
        /// <remarks/>
        public sbyte tpInsc {
            get {
                return this.tpInscField;
            }
            set {
                this.tpInscField = value;
            }
        }
        
        /// <remarks/>
        public string nrInsc {
            get {
                return this.nrInscField;
            }
            set {
                this.nrInscField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public partial class TIdeEveTrab {
        
        private sbyte indRetifField;
        
        private string nrReciboField;
        
        private sbyte tpAmbField;
        
        private sbyte procEmiField;
        
        private string verProcField;
        
        /// <remarks/>
        public sbyte indRetif {
            get {
                return this.indRetifField;
            }
            set {
                this.indRetifField = value;
            }
        }
        
        /// <remarks/>
        public string nrRecibo {
            get {
                return this.nrReciboField;
            }
            set {
                this.nrReciboField = value;
            }
        }
        
        /// <remarks/>
        public sbyte tpAmb {
            get {
                return this.tpAmbField;
            }
            set {
                this.tpAmbField = value;
            }
        }
        
        /// <remarks/>
        public sbyte procEmi {
            get {
                return this.procEmiField;
            }
            set {
                this.procEmiField = value;
            }
        }
        
        /// <remarks/>
        public string verProc {
            get {
                return this.verProcField;
            }
            set {
                this.verProcField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class X509DataType {
        
        private byte[] x509CertificateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] X509Certificate {
            get {
                return this.x509CertificateField;
            }
            set {
                this.x509CertificateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class KeyInfoType {
        
        private X509DataType x509DataField;
        
        private string idField;
        
        /// <remarks/>
        public X509DataType X509Data {
            get {
                return this.x509DataField;
            }
            set {
                this.x509DataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignatureValueType {
        
        private string idField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class TransformType {
        
        private string[] xPathField;
        
        private TTransformURI algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("XPath")]
        public string[] XPath {
            get {
                return this.xPathField;
            }
            set {
                this.xPathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public TTransformURI Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public enum TTransformURI {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/2000/09/xmldsig#enveloped-signature")]
        httpwwww3org200009xmldsigenvelopedsignature,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("http://www.w3.org/TR/2001/REC-xml-c14n-20010315")]
        httpwwww3orgTR2001RECxmlc14n20010315,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class ReferenceType {
        
        private TransformType[] transformsField;
        
        private ReferenceTypeDigestMethod digestMethodField;
        
        private byte[] digestValueField;
        
        private string idField;
        
        private string uRIField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable=false)]
        public TransformType[] Transforms {
            get {
                return this.transformsField;
            }
            set {
                this.transformsField = value;
            }
        }
        
        /// <remarks/>
        public ReferenceTypeDigestMethod DigestMethod {
            get {
                return this.digestMethodField;
            }
            set {
                this.digestMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] DigestValue {
            get {
                return this.digestValueField;
            }
            set {
                this.digestValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string URI {
            get {
                return this.uRIField;
            }
            set {
                this.uRIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class ReferenceTypeDigestMethod {
        
        private string algorithmField;
        
        public ReferenceTypeDigestMethod() {
            this.algorithmField = "http://www.w3.org/2000/09/xmldsig#sha1";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignedInfoTypeSignatureMethod {
        
        private string algorithmField;
        
        public SignedInfoTypeSignatureMethod() {
            this.algorithmField = "http://www.w3.org/2000/09/xmldsig#rsa-sha1";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm {
            get {
                return this.algorithmField;
            }
            set {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00", IsNullable=false)]
    public partial class eSocial {
        
        private eSocialEvtTSVInicio evtTSVInicioField;
        
        private SignatureType signatureField;
        
        /// <remarks/>
        public eSocialEvtTSVInicio evtTSVInicio {
            get {
                return this.evtTSVInicioField;
            }
            set {
                this.evtTSVInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public SignatureType Signature {
            get {
                return this.signatureField;
            }
            set {
                this.signatureField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public partial class eSocialEvtTSVInicio {
        
        private TIdeEveTrab ideEventoField;
        
        private TEmpregador ideEmpregadorField;
        
        private eSocialEvtTSVInicioTrabalhador trabalhadorField;
        
        private eSocialEvtTSVInicioInfoTSVInicio infoTSVInicioField;
        
        private string idField;
        
        /// <remarks/>
        public TIdeEveTrab ideEvento {
            get {
                return this.ideEventoField;
            }
            set {
                this.ideEventoField = value;
            }
        }
        
        /// <remarks/>
        public TEmpregador ideEmpregador {
            get {
                return this.ideEmpregadorField;
            }
            set {
                this.ideEmpregadorField = value;
            }
        }
        
        /// <remarks/>
        public eSocialEvtTSVInicioTrabalhador trabalhador {
            get {
                return this.trabalhadorField;
            }
            set {
                this.trabalhadorField = value;
            }
        }
        
        /// <remarks/>
        public eSocialEvtTSVInicioInfoTSVInicio infoTSVInicio {
            get {
                return this.infoTSVInicioField;
            }
            set {
                this.infoTSVInicioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public partial class eSocialEvtTSVInicioTrabalhador {
        
        private string cpfTrabField;
        
        private string nisTrabField;
        
        private string nmTrabField;
        
        private string sexoField;
        
        private sbyte racaCorField;
        
        private sbyte estCivField;
        
        private bool estCivFieldSpecified;
        
        private string grauInstrField;
        
        private eSocialEvtTSVInicioTrabalhadorNascimento nascimentoField;
        
        private eSocialEvtTSVInicioTrabalhadorDocumentos documentosField;
        
        private eSocialEvtTSVInicioTrabalhadorEndereco enderecoField;
        
        private TTrabEstrang trabEstrangeiroField;
        
        private eSocialEvtTSVInicioTrabalhadorInfoDeficiencia infoDeficienciaField;
        
        private eSocialEvtTSVInicioTrabalhadorDependente[] dependenteField;
        
        private TContato contatoField;
        
        /// <remarks/>
        public string cpfTrab {
            get {
                return this.cpfTrabField;
            }
            set {
                this.cpfTrabField = value;
            }
        }
        
        /// <remarks/>
        public string nisTrab {
            get {
                return this.nisTrabField;
            }
            set {
                this.nisTrabField = value;
            }
        }
        
        /// <remarks/>
        public string nmTrab {
            get {
                return this.nmTrabField;
            }
            set {
                this.nmTrabField = value;
            }
        }
        
        /// <remarks/>
        public string sexo {
            get {
                return this.sexoField;
            }
            set {
                this.sexoField = value;
            }
        }
        
        /// <remarks/>
        public sbyte racaCor {
            get {
                return this.racaCorField;
            }
            set {
                this.racaCorField = value;
            }
        }
        
        /// <remarks/>
        public sbyte estCiv {
            get {
                return this.estCivField;
            }
            set {
                this.estCivField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estCivSpecified {
            get {
                return this.estCivFieldSpecified;
            }
            set {
                this.estCivFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string grauInstr {
            get {
                return this.grauInstrField;
            }
            set {
                this.grauInstrField = value;
            }
        }
        
        /// <remarks/>
        public eSocialEvtTSVInicioTrabalhadorNascimento nascimento {
            get {
                return this.nascimentoField;
            }
            set {
                this.nascimentoField = value;
            }
        }
        
        /// <remarks/>
        public eSocialEvtTSVInicioTrabalhadorDocumentos documentos {
            get {
                return this.documentosField;
            }
            set {
                this.documentosField = value;
            }
        }
        
        /// <remarks/>
        public eSocialEvtTSVInicioTrabalhadorEndereco endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
            }
        }
        
        /// <remarks/>
        public TTrabEstrang trabEstrangeiro {
            get {
                return this.trabEstrangeiroField;
            }
            set {
                this.trabEstrangeiroField = value;
            }
        }
        
        /// <remarks/>
        public eSocialEvtTSVInicioTrabalhadorInfoDeficiencia infoDeficiencia {
            get {
                return this.infoDeficienciaField;
            }
            set {
                this.infoDeficienciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dependente")]
        public eSocialEvtTSVInicioTrabalhadorDependente[] dependente {
            get {
                return this.dependenteField;
            }
            set {
                this.dependenteField = value;
            }
        }
        
        /// <remarks/>
        public TContato contato {
            get {
                return this.contatoField;
            }
            set {
                this.contatoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public partial class eSocialEvtTSVInicioTrabalhadorNascimento {
        
        private System.DateTime dtNasctoField;
        
        private string codMunicField;
        
        private string ufField;
        
        private string paisNasctoField;
        
        private string paisNacField;
        
        private string nmMaeField;
        
        private string nmPaiField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dtNascto {
            get {
                return this.dtNasctoField;
            }
            set {
                this.dtNasctoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string codMunic {
            get {
                return this.codMunicField;
            }
            set {
                this.codMunicField = value;
            }
        }
        
        /// <remarks/>
        public string uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
        
        /// <remarks/>
        public string paisNascto {
            get {
                return this.paisNasctoField;
            }
            set {
                this.paisNasctoField = value;
            }
        }
        
        /// <remarks/>
        public string paisNac {
            get {
                return this.paisNacField;
            }
            set {
                this.paisNacField = value;
            }
        }
        
        /// <remarks/>
        public string nmMae {
            get {
                return this.nmMaeField;
            }
            set {
                this.nmMaeField = value;
            }
        }
        
        /// <remarks/>
        public string nmPai {
            get {
                return this.nmPaiField;
            }
            set {
                this.nmPaiField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public partial class eSocialEvtTSVInicioTrabalhadorDocumentos {
        
        private TCtps cTPSField;
        
        private TRic rICField;
        
        private TRg rgField;
        
        private TRne rNEField;
        
        private TOc ocField;
        
        private TCnh cNHField;
        
        /// <remarks/>
        public TCtps CTPS {
            get {
                return this.cTPSField;
            }
            set {
                this.cTPSField = value;
            }
        }
        
        /// <remarks/>
        public TRic RIC {
            get {
                return this.rICField;
            }
            set {
                this.rICField = value;
            }
        }
        
        /// <remarks/>
        public TRg RG {
            get {
                return this.rgField;
            }
            set {
                this.rgField = value;
            }
        }
        
        /// <remarks/>
        public TRne RNE {
            get {
                return this.rNEField;
            }
            set {
                this.rNEField = value;
            }
        }
        
        /// <remarks/>
        public TOc OC {
            get {
                return this.ocField;
            }
            set {
                this.ocField = value;
            }
        }
        
        /// <remarks/>
        public TCnh CNH {
            get {
                return this.cNHField;
            }
            set {
                this.cNHField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public partial class eSocialEvtTSVInicioTrabalhadorEndereco {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("brasil", typeof(TEnderecoBrasil))]
        [System.Xml.Serialization.XmlElementAttribute("exterior", typeof(TEnderecoExterior))]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public partial class eSocialEvtTSVInicioTrabalhadorInfoDeficiencia {
        
        private eSocialEvtTSVInicioTrabalhadorInfoDeficienciaDefFisica defFisicaField;
        
        private eSocialEvtTSVInicioTrabalhadorInfoDeficienciaDefVisual defVisualField;
        
        private eSocialEvtTSVInicioTrabalhadorInfoDeficienciaDefAuditiva defAuditivaField;
        
        private eSocialEvtTSVInicioTrabalhadorInfoDeficienciaDefMental defMentalField;
        
        private eSocialEvtTSVInicioTrabalhadorInfoDeficienciaDefIntelectual defIntelectualField;
        
        private eSocialEvtTSVInicioTrabalhadorInfoDeficienciaReabReadap reabReadapField;
        
        private string observacaoField;
        
        /// <remarks/>
        public eSocialEvtTSVInicioTrabalhadorInfoDeficienciaDefFisica defFisica {
            get {
                return this.defFisicaField;
            }
            set {
                this.defFisicaField = value;
            }
        }
        
        /// <remarks/>
        public eSocialEvtTSVInicioTrabalhadorInfoDeficienciaDefVisual defVisual {
            get {
                return this.defVisualField;
            }
            set {
                this.defVisualField = value;
            }
        }
        
        /// <remarks/>
        public eSocialEvtTSVInicioTrabalhadorInfoDeficienciaDefAuditiva defAuditiva {
            get {
                return this.defAuditivaField;
            }
            set {
                this.defAuditivaField = value;
            }
        }
        
        /// <remarks/>
        public eSocialEvtTSVInicioTrabalhadorInfoDeficienciaDefMental defMental {
            get {
                return this.defMentalField;
            }
            set {
                this.defMentalField = value;
            }
        }
        
        /// <remarks/>
        public eSocialEvtTSVInicioTrabalhadorInfoDeficienciaDefIntelectual defIntelectual {
            get {
                return this.defIntelectualField;
            }
            set {
                this.defIntelectualField = value;
            }
        }
        
        /// <remarks/>
        public eSocialEvtTSVInicioTrabalhadorInfoDeficienciaReabReadap reabReadap {
            get {
                return this.reabReadapField;
            }
            set {
                this.reabReadapField = value;
            }
        }
        
        /// <remarks/>
        public string observacao {
            get {
                return this.observacaoField;
            }
            set {
                this.observacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public enum eSocialEvtTSVInicioTrabalhadorInfoDeficienciaDefFisica {
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public enum eSocialEvtTSVInicioTrabalhadorInfoDeficienciaDefVisual {
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public enum eSocialEvtTSVInicioTrabalhadorInfoDeficienciaDefAuditiva {
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public enum eSocialEvtTSVInicioTrabalhadorInfoDeficienciaDefMental {
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public enum eSocialEvtTSVInicioTrabalhadorInfoDeficienciaDefIntelectual {
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public enum eSocialEvtTSVInicioTrabalhadorInfoDeficienciaReabReadap {
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public partial class eSocialEvtTSVInicioTrabalhadorDependente {
        
        private string tpDepField;
        
        private string nmDepField;
        
        private System.DateTime dtNasctoField;
        
        private string cpfDepField;
        
        private eSocialEvtTSVInicioTrabalhadorDependenteDepIRRF depIRRFField;
        
        private eSocialEvtTSVInicioTrabalhadorDependenteDepSF depSFField;
        
        /// <remarks/>
        public string tpDep {
            get {
                return this.tpDepField;
            }
            set {
                this.tpDepField = value;
            }
        }
        
        /// <remarks/>
        public string nmDep {
            get {
                return this.nmDepField;
            }
            set {
                this.nmDepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dtNascto {
            get {
                return this.dtNasctoField;
            }
            set {
                this.dtNasctoField = value;
            }
        }
        
        /// <remarks/>
        public string cpfDep {
            get {
                return this.cpfDepField;
            }
            set {
                this.cpfDepField = value;
            }
        }
        
        /// <remarks/>
        public eSocialEvtTSVInicioTrabalhadorDependenteDepIRRF depIRRF {
            get {
                return this.depIRRFField;
            }
            set {
                this.depIRRFField = value;
            }
        }
        
        /// <remarks/>
        public eSocialEvtTSVInicioTrabalhadorDependenteDepSF depSF {
            get {
                return this.depSFField;
            }
            set {
                this.depSFField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public enum eSocialEvtTSVInicioTrabalhadorDependenteDepIRRF {
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public enum eSocialEvtTSVInicioTrabalhadorDependenteDepSF {
        
        /// <remarks/>
        S,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public partial class eSocialEvtTSVInicioInfoTSVInicio {
        
        private string codCategField;
        
        private System.DateTime dtInicioField;
        
        private sbyte natAtividadeField;
        
        private bool natAtividadeFieldSpecified;
        
        private eSocialEvtTSVInicioInfoTSVInicioInfoComplementares infoComplementaresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string codCateg {
            get {
                return this.codCategField;
            }
            set {
                this.codCategField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dtInicio {
            get {
                return this.dtInicioField;
            }
            set {
                this.dtInicioField = value;
            }
        }
        
        /// <remarks/>
        public sbyte natAtividade {
            get {
                return this.natAtividadeField;
            }
            set {
                this.natAtividadeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool natAtividadeSpecified {
            get {
                return this.natAtividadeFieldSpecified;
            }
            set {
                this.natAtividadeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public eSocialEvtTSVInicioInfoTSVInicioInfoComplementares infoComplementares {
            get {
                return this.infoComplementaresField;
            }
            set {
                this.infoComplementaresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public partial class eSocialEvtTSVInicioInfoTSVInicioInfoComplementares {
        
        private eSocialEvtTSVInicioInfoTSVInicioInfoComplementaresCargoFuncao cargoFuncaoField;
        
        private TRemun remuneracaoField;
        
        private TFgts fgtsField;
        
        private eSocialEvtTSVInicioInfoTSVInicioInfoComplementaresInfoDirigenteSindical infoDirigenteSindicalField;
        
        private TCessaoTrab infoTrabCedidoField;
        
        private eSocialEvtTSVInicioInfoTSVInicioInfoComplementaresInfoEstagiario infoEstagiarioField;
        
        /// <remarks/>
        public eSocialEvtTSVInicioInfoTSVInicioInfoComplementaresCargoFuncao cargoFuncao {
            get {
                return this.cargoFuncaoField;
            }
            set {
                this.cargoFuncaoField = value;
            }
        }
        
        /// <remarks/>
        public TRemun remuneracao {
            get {
                return this.remuneracaoField;
            }
            set {
                this.remuneracaoField = value;
            }
        }
        
        /// <remarks/>
        public TFgts fgts {
            get {
                return this.fgtsField;
            }
            set {
                this.fgtsField = value;
            }
        }
        
        /// <remarks/>
        public eSocialEvtTSVInicioInfoTSVInicioInfoComplementaresInfoDirigenteSindical infoDirigenteSindical {
            get {
                return this.infoDirigenteSindicalField;
            }
            set {
                this.infoDirigenteSindicalField = value;
            }
        }
        
        /// <remarks/>
        public TCessaoTrab infoTrabCedido {
            get {
                return this.infoTrabCedidoField;
            }
            set {
                this.infoTrabCedidoField = value;
            }
        }
        
        /// <remarks/>
        public eSocialEvtTSVInicioInfoTSVInicioInfoComplementaresInfoEstagiario infoEstagiario {
            get {
                return this.infoEstagiarioField;
            }
            set {
                this.infoEstagiarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public partial class eSocialEvtTSVInicioInfoTSVInicioInfoComplementaresCargoFuncao {
        
        private string codCargoField;
        
        private string codFuncaoField;
        
        /// <remarks/>
        public string codCargo {
            get {
                return this.codCargoField;
            }
            set {
                this.codCargoField = value;
            }
        }
        
        /// <remarks/>
        public string codFuncao {
            get {
                return this.codFuncaoField;
            }
            set {
                this.codFuncaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public partial class eSocialEvtTSVInicioInfoTSVInicioInfoComplementaresInfoDirigenteSindical {
        
        private string categOrigField;
        
        private string cnpjOrigemField;
        
        private System.DateTime dtAdmOrigField;
        
        private bool dtAdmOrigFieldSpecified;
        
        private string matricOrigField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string categOrig {
            get {
                return this.categOrigField;
            }
            set {
                this.categOrigField = value;
            }
        }
        
        /// <remarks/>
        public string cnpjOrigem {
            get {
                return this.cnpjOrigemField;
            }
            set {
                this.cnpjOrigemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dtAdmOrig {
            get {
                return this.dtAdmOrigField;
            }
            set {
                this.dtAdmOrigField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dtAdmOrigSpecified {
            get {
                return this.dtAdmOrigFieldSpecified;
            }
            set {
                this.dtAdmOrigFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string matricOrig {
            get {
                return this.matricOrigField;
            }
            set {
                this.matricOrigField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public partial class eSocialEvtTSVInicioInfoTSVInicioInfoComplementaresInfoEstagiario {
        
        private string natEstagioField;
        
        private sbyte nivEstagioField;
        
        private string areaAtuacaoField;
        
        private string nrApolField;
        
        private decimal vlrBolsaField;
        
        private bool vlrBolsaFieldSpecified;
        
        private System.DateTime dtPrevTermField;
        
        private eSocialEvtTSVInicioInfoTSVInicioInfoComplementaresInfoEstagiarioInstEnsino instEnsinoField;
        
        private eSocialEvtTSVInicioInfoTSVInicioInfoComplementaresInfoEstagiarioAgeIntegracao ageIntegracaoField;
        
        private eSocialEvtTSVInicioInfoTSVInicioInfoComplementaresInfoEstagiarioSupervisorEstagio supervisorEstagioField;
        
        /// <remarks/>
        public string natEstagio {
            get {
                return this.natEstagioField;
            }
            set {
                this.natEstagioField = value;
            }
        }
        
        /// <remarks/>
        public sbyte nivEstagio {
            get {
                return this.nivEstagioField;
            }
            set {
                this.nivEstagioField = value;
            }
        }
        
        /// <remarks/>
        public string areaAtuacao {
            get {
                return this.areaAtuacaoField;
            }
            set {
                this.areaAtuacaoField = value;
            }
        }
        
        /// <remarks/>
        public string nrApol {
            get {
                return this.nrApolField;
            }
            set {
                this.nrApolField = value;
            }
        }
        
        /// <remarks/>
        public decimal vlrBolsa {
            get {
                return this.vlrBolsaField;
            }
            set {
                this.vlrBolsaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool vlrBolsaSpecified {
            get {
                return this.vlrBolsaFieldSpecified;
            }
            set {
                this.vlrBolsaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime dtPrevTerm {
            get {
                return this.dtPrevTermField;
            }
            set {
                this.dtPrevTermField = value;
            }
        }
        
        /// <remarks/>
        public eSocialEvtTSVInicioInfoTSVInicioInfoComplementaresInfoEstagiarioInstEnsino instEnsino {
            get {
                return this.instEnsinoField;
            }
            set {
                this.instEnsinoField = value;
            }
        }
        
        /// <remarks/>
        public eSocialEvtTSVInicioInfoTSVInicioInfoComplementaresInfoEstagiarioAgeIntegracao ageIntegracao {
            get {
                return this.ageIntegracaoField;
            }
            set {
                this.ageIntegracaoField = value;
            }
        }
        
        /// <remarks/>
        public eSocialEvtTSVInicioInfoTSVInicioInfoComplementaresInfoEstagiarioSupervisorEstagio supervisorEstagio {
            get {
                return this.supervisorEstagioField;
            }
            set {
                this.supervisorEstagioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public partial class eSocialEvtTSVInicioInfoTSVInicioInfoComplementaresInfoEstagiarioInstEnsino {
        
        private string cnpjInstEnsinoField;
        
        private string nmRazaoField;
        
        private string dscLogradField;
        
        private string nrLogradField;
        
        private string bairroField;
        
        private string cepField;
        
        private string codMunicField;
        
        private string ufField;
        
        /// <remarks/>
        public string cnpjInstEnsino {
            get {
                return this.cnpjInstEnsinoField;
            }
            set {
                this.cnpjInstEnsinoField = value;
            }
        }
        
        /// <remarks/>
        public string nmRazao {
            get {
                return this.nmRazaoField;
            }
            set {
                this.nmRazaoField = value;
            }
        }
        
        /// <remarks/>
        public string dscLograd {
            get {
                return this.dscLogradField;
            }
            set {
                this.dscLogradField = value;
            }
        }
        
        /// <remarks/>
        public string nrLograd {
            get {
                return this.nrLogradField;
            }
            set {
                this.nrLogradField = value;
            }
        }
        
        /// <remarks/>
        public string bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string codMunic {
            get {
                return this.codMunicField;
            }
            set {
                this.codMunicField = value;
            }
        }
        
        /// <remarks/>
        public string uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public partial class eSocialEvtTSVInicioInfoTSVInicioInfoComplementaresInfoEstagiarioAgeIntegracao {
        
        private string cnpjAgntIntegField;
        
        private string nmRazaoField;
        
        private string dscLogradField;
        
        private string nrLogradField;
        
        private string bairroField;
        
        private string cepField;
        
        private string codMunicField;
        
        private string ufField;
        
        /// <remarks/>
        public string cnpjAgntInteg {
            get {
                return this.cnpjAgntIntegField;
            }
            set {
                this.cnpjAgntIntegField = value;
            }
        }
        
        /// <remarks/>
        public string nmRazao {
            get {
                return this.nmRazaoField;
            }
            set {
                this.nmRazaoField = value;
            }
        }
        
        /// <remarks/>
        public string dscLograd {
            get {
                return this.dscLogradField;
            }
            set {
                this.dscLogradField = value;
            }
        }
        
        /// <remarks/>
        public string nrLograd {
            get {
                return this.nrLogradField;
            }
            set {
                this.nrLogradField = value;
            }
        }
        
        /// <remarks/>
        public string bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string codMunic {
            get {
                return this.codMunicField;
            }
            set {
                this.codMunicField = value;
            }
        }
        
        /// <remarks/>
        public string uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "0.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.esocial.gov.br/schema/evt/evtTSVInicio/v02_01_00")]
    public partial class eSocialEvtTSVInicioInfoTSVInicioInfoComplementaresInfoEstagiarioSupervisorEstagio {
        
        private string cpfSupervisorField;
        
        private string nmSupervField;
        
        /// <remarks/>
        public string cpfSupervisor {
            get {
                return this.cpfSupervisorField;
            }
            set {
                this.cpfSupervisorField = value;
            }
        }
        
        /// <remarks/>
        public string nmSuperv {
            get {
                return this.nmSupervField;
            }
            set {
                this.nmSupervField = value;
            }
        }
    }
}
